#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times and "Hi" in 9th iteration times
cont=0
while [ $cont -lt 10 ];
do
    if [ $cont -eq 9 ]
    then
echo "Hi"
    fi
    echo "Best School"
    ((cont++)) || true
done
