#!/usr/bin/env bash
# script displaying " good luck" "Best School" "bad luck" 
CONTER=0
while [ $CONTER -lt 10 ];
do
    if [ $CONTER -eq 3 ]
    then
echo "bad luck"
    elif [ $CONTER -eq 7 ]
    then
echo "good luck"
    else
echo "Best School"
    fi
    ((CONTER++)) || true
done
